In [1]:
!pip install numpy
!pip install matplotlib
!pip install pandas


[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python3.11 -m pip install --upgrade pip

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python3.11 -m pip install --upgrade pip
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.3/11.3 MB 221.6 kB/s eta 0:00:0000:0100:02
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 505.5/505.5 kB 184.4 kB/s eta 0:00:00a 0:00:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 345.4/345.4 kB 224.7 kB/s eta 0:00:0000:0100:01

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python3.11 -m pip install --upgrade pip


In [1]:
import numpy as np
np.seterr(all='warn')

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

In [135]:
import sys
sys.setrecursionlimit(20000)

### 1. Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы. 
Для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [273]:
'''
Тестовые данные
'''
X = [np.array([[1, 0, 1],
               [2, 0, 2],
               [3, 0, 3],
               [4, 4, 4]]),
     np.array([[0, 1],
               [1, 0]]),
     np.array([[0, 0, 1, 2], 
               [2, 0, 2, 4], 
               [3, 0, 0, 6], 
               [4, 4, 4, 7]])]

In [309]:
def calcDiagFor(mat):
    '''
    Пример 1.1 Через цикл
    '''
    composition = 1.0
    SIZE = min(len(mat), len(mat[0]))
    for i in range(SIZE): 
        if float(mat[i][i]) != 0.0:
            composition *= float(mat[i][i])
    return composition

In [313]:
def calcDiagReq(mat, i = 0):
    '''
    Пример 1.2 Через рекурсию
    '''
    SIZE = min(len(mat), len(mat[0]))
    if i == SIZE:
        return 0.0
    
    if float(mat[i][i]) != 0.0:
        nextElem = float(calcDiagReq(mat, (i + 1)))
        if nextElem == 0.0:  # Проверка наличия не нулевых элементов
            return float(mat[i][i])
        else:
            return (float(mat[i][i]) * nextElem)
    return float(calcDiagReq(mat, (i + 1)))

In [320]:
def calcDiagNp(mat):
    '''
    Пример 1.3 Возьмем диагональ через метод из numpy и после пройдемся по ней
    '''
    arr = np.diag(mat)
    composition = 1.0
    for i in range(len(arr)):
        if float(arr[i]) != 0.0:
            composition *= float(arr[i])
    return composition

In [318]:
for it in X:
    if ( calcDiagFor(it) != calcDiagReq(it) != calcDiagNp(it) ):
        print(it)
        print(f'calcDiagFor = {calcDiagFor(it)}')
        print(f'calcDiagReq = {calcDiagReq(it)}')
        print(f'calcDiagNp = {calcDiagNp(it)}')
        raise Exception('Значения не равны')
print('SUCCESS')

SUCCESS


## Временные тесты

In [322]:
X = [  # Решил на этих массивах проверить и были ошибки, 
       # так как слишком большие значения возникали и было переполнение
    np.random.randint(-2, 2, (100, 100)),
    np.random.randint(-2, 2, (1000, 1000)),
    np.random.randint(-2, 2, (10000, 10000))
]

100

In [323]:
%%timeit
calcDiagFor(X[0])

25.5 µs ± 82.1 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [324]:
%%timeit
calcDiagReq(X[0])

53.7 µs ± 143 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [325]:
%%timeit
calcDiagNp(X[0])

14.2 µs ± 17.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


1000

In [326]:
%%timeit
calcDiagFor(X[1])

263 µs ± 715 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [327]:
%%timeit
calcDiagReq(X[1])

553 µs ± 442 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [328]:
%%timeit
calcDiagNp(X[1])

145 µs ± 401 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


10000

In [329]:
%%timeit
calcDiagFor(X[2])

2.65 ms ± 3.74 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [330]:
%%timeit
calcDiagReq(X[2])

5.56 ms ± 17.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [331]:
%%timeit
calcDiagNp(X[2])

1.47 ms ± 1.03 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


## Вывод по заданию 1

Рекурсии не эффективна. Функция с прямым проходом по матрице оказалась медленнее, чем взятие диагонали, и последующий проход по вектору. numpy мощь.

### 2. Дана матрица X и два вектора одинаковой длины i и j. Построить вектор np.array([X[i[0], j[0]], X[i[1], j[1]], ... , X[i[N-1], j[N-1]]]).

In [3]:
x = np.random.randint(-20, 20, size=(5, 5))
v1 = np.random.randint(0, 5, 5)
v2 = np.random.randint(0, 5, 5)

In [9]:
def VectorBuildFor(x, v1, v2):
    '''
    Пример 2.1 Через цикл
    '''
    v = []
    for i in range(len(v1)):
        v.append(x[v1[i]][v2[i]])
    return np.array(v)

In [10]:
def VectorBuildNp(x, v1, v2):
    '''
    Пример 2.2 возмоностью вектора
    '''
    return x[v1, v2]

In [11]:
def VectorBuildGenerator(x, v1, v2):
    '''
    Пример 2.3 Генератором
    '''
    return np.array([x[v1[i]][v2[i]] for i in range(len(v1))])

In [12]:
print(VectorBuildFor(x, v1, v2))
print(VectorBuildNp(x, v1, v2))
print(VectorBuildGenerator(x, v1, v2))

[ 2 -3 -4 -1 -3]
[ 2 -3 -4 -1 -3]
[ 2 -3 -4 -1 -3]


## Временной тест

100

In [13]:
x = np.random.randint(-20, 20, size=(100, 100))
v1 = np.random.randint(0, 100, 100)
v2 = np.random.randint(0, 100, 100)

In [14]:
%%timeit
VectorBuildFor(x, v1, v2)

29.5 µs ± 98.3 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [15]:
%%timeit
VectorBuildNp(x, v1, v2)

1.18 µs ± 3.74 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [17]:
%%timeit
VectorBuildGenerator(x, v1, v2)

29.7 µs ± 263 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


1000

In [18]:
x = np.random.randint(-20, 20, size=(1000, 1000))
v1 = np.random.randint(0, 1000, 1000)
v2 = np.random.randint(0, 1000, 1000)

In [19]:
%%timeit
VectorBuildFor(x, v1, v2)

322 µs ± 1.63 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [20]:
%%timeit
VectorBuildNp(x, v1, v2)

5.81 µs ± 193 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [21]:
%%timeit
VectorBuildGenerator(x, v1, v2)

319 µs ± 782 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


10000

In [22]:
x = np.random.randint(-20, 20, size=(10000, 10000))
v1 = np.random.randint(0, 10000, 10000)
v2 = np.random.randint(0, 10000, 10000)

In [23]:
%%timeit
VectorBuildFor(x, v1, v2)

3.4 ms ± 73.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [24]:
%%timeit
VectorBuildNp(x, v1, v2)

57.3 µs ± 358 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [25]:
%%timeit
VectorBuildGenerator(x, v1, v2)

3.24 ms ± 64.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Вывод по заданию 2
Методы из numpy радиакально быстрее чем код написанный на python. Генераторы по скорости с развернутой конструкцией +- одинаковы, на уровне погрешености

### 3. Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество. 
Для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [332]:
x = np.array([1, 2, 2, 4])
y = np.array([4, 2, 1, 2])

x2 = np.array([2, 2, 3, 4])
y2 = np.array([1, 2, 3, 4])

In [217]:
def CheckMultiSetFor(x, y):
    '''
    Пример 3.1 Просто перебор циклом, с удалением элементов, которые были.

    Специально сделал не эффективным, для того чтобы посмотреть на сколько медленным получится
    '''
    posFirst = []
    for elem in x:
        posFirst = np.where(y == elem)[0]
        if len(posFirst) != 0:
            y = np.delete(y, posFirst[0])
        else:
            return False
    return True

In [218]:
def CheckMultiSetSet(x, y):
    '''
    Пример 3.2 Переносим Set воспользуемся методом unique из numpy, после сравним результаты
    '''
    if len(x) != len(y):
        return False
    left = np.unique(x, return_counts=True)
    right = np.unique(y, return_counts=True)
    if len(left[0]) != len(right[0]):
        return False
    return ((len(set(left[0] == right[0])) == 1) and (len(set(left[1] == right[1])) == 1))

In [219]:
def CheckMultiSetSort(x, y):
    '''
    Пример 3.3 Сортируем список и сравниваем их
    '''
    x.sort()
    y.sort()
    return (len(set(x == y)) == 1)

In [221]:
print(CheckMultiSetFor(x, y))
print(CheckMultiSetFor(x2, y2))
print(CheckMultiSetSet(x, y))
print(CheckMultiSetSet(x2, y2))
print(CheckMultiSetSort(x, y))
print(CheckMultiSetSort(x2, y2))

True
False
True
False
True
False


## Тест времени

In [223]:
X = [
    np.random.randint(-20, 20, 100),
    np.random.randint(-20, 20, 1000),
    np.random.randint(-20, 20, 10000)
]
Y = [
    np.random.randint(-20, 20, 100),
    np.random.randint(-20, 20, 1000),
    np.random.randint(-20, 20, 10000)
]

100

In [224]:
%%timeit
CheckMultiSetFor(X[0], Y[0])

26.2 µs ± 173 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [225]:
%%timeit
CheckMultiSetSet(X[0], Y[0])

13.4 µs ± 19.4 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [226]:
%%timeit
CheckMultiSetSort(X[0], Y[0])

2.71 µs ± 10.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


1000

In [227]:
%%timeit
CheckMultiSetFor(X[1], Y[1])

2.32 ms ± 9.47 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [228]:
%%timeit
CheckMultiSetSet(X[1], Y[1])

31.1 µs ± 2.2 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [229]:
%%timeit
CheckMultiSetSort(X[1], Y[1])

21.6 µs ± 87.7 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


10000

In [230]:
%%timeit
CheckMultiSetFor(X[2], Y[2])

69.1 ms ± 158 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [231]:
%%timeit
CheckMultiSetSet(X[2], Y[2])

529 µs ± 1.87 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [232]:
%%timeit
CheckMultiSetSort(X[2], Y[2])

239 µs ± 494 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


## Вывод по заданию 3

На малых объемах векторов метод через цикл, с удалением элементов еще не так плох, просто чуть медленный, но при большом объеме не использовать! Из двух других самым быстрым явлется с сортировкой, в python используется TimSort, тогда сложность данного метода
O(n * logn)

### 4. Найти максимальный элемент в векторе x среди элементов, перед которыми стоит нулевой. 
Для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [338]:
x1 = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])  # 5
x2 = np.array([6, 100, 0, 3, 0, 2, 0, 7, 0])  # 7
x3 = np.array([0, 1]) # 1

In [243]:
def findZeroMaxGoTo(x):
    '''
    Пример 4.1 Прямой проход, сложность должна быть O(n)
    '''
    maxE = 0.0
    checkThis = False
    for i in x:
        if checkThis:
            if maxE < i:
                maxE = i

        if i == 0.0:
            checkThis = True
        else:
            checkThis = False
    return maxE

In [245]:
def findZeroMaxReq(x, i = 0, maxE = 0.0, checkThis = False):
    '''
    Пример 4.2 Рекурсивная реализация метода из примера 4.1
    '''
    SIZE = len(x)
    if i == SIZE:
        return maxE

    if checkThis:
        if maxE < x[i]:
            maxE = x[i]
    
    if x[i] == 0.0:
        checkThis = True
    else:
        checkThis = False

    return findZeroMaxReq(x, (i + 1), maxE, checkThis)

In [350]:
def findZeroMaxList(x):
    '''
    Пример 4.3 Прямой проход, с сохранением элементов, которые удовлетворяют условию. 
    После обратботка полученного списка, чтобы максимальное найти. Сложность O(2*n)
    '''
    maxList = []
    checkThis = False
    for i in x:
        if checkThis:
            maxList.append(i)

        if i == 0.0:
            checkThis = True
        else:
            checkThis = False
    return np.max(maxList)

In [339]:
print(findZeroMaxGoTo(x1))
print(findZeroMaxGoTo(x2))
print(findZeroMaxGoTo(x3))
print(findZeroMaxReq(x1))
print(findZeroMaxReq(x2))
print(findZeroMaxReq(x3))
print(findZeroMaxList(x1))
print(findZeroMaxList(x2))
print(findZeroMaxList(x3))

5
7
1
5
7
1
5
7
1


## Тест на время

In [340]:
X = [
    np.random.randint(-100, 100, 100),
    np.random.randint(-100, 100, 1000),
    np.random.randint(-100, 100, 10000)
]

100

In [341]:
%%timeit
findZeroMaxGoTo(X[0])

83.8 µs ± 299 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [342]:
%%timeit
findZeroMaxReq(X[0])

98 µs ± 125 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [351]:
%%timeit
findZeroMaxList(X[0])

85.5 µs ± 33.3 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


1000

In [344]:
%%timeit
findZeroMaxGoTo(X[1])

827 µs ± 564 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [345]:
%%timeit
findZeroMaxReq(X[1])

985 µs ± 6.01 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [352]:
%%timeit
findZeroMaxList(X[1])

825 µs ± 1.73 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


10000

In [347]:
%%timeit
findZeroMaxGoTo(X[2])

8.25 ms ± 8.42 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [348]:
%%timeit
findZeroMaxReq(X[2])

9.71 ms ± 17.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [353]:
%%timeit
findZeroMaxList(X[2])

8.2 ms ± 23 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Вывод по 4 номеру

Как было установлено ранее(задание 1) рекурсивные методы работают медленно, данный тест это подтвердил.
Методы findZeroMaxList и findZeroMaxGoTo работают одинаково, на уровне погрешности. Их сложность O(n).

### 5. Дан трёхмерный массив, содержащий изображение, размера (height, width, numChannels), а также вектор длины numChannels. Сложить каналы изображения с указанными весами, и вернуть результат в виде матрицы размера (height, width). Считать реальное изображение можно при помощи функции scipy.misc.imread (если изображение не в формате png, установите пакет pillow: conda install pillow). Преобразуйте цветное изображение в оттенки серого, использовав коэффициенты np.array([0.299, 0.587, 0.114]).

In [493]:
!pip install scipy
!pip install imageio
!pip install pillow


[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python3.11 -m pip install --upgrade pip

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python3.11 -m pip install --upgrade pip

[notice] A new release of pip is available: 23.3.1 -> 24.0
[notice] To update, run: python3.11 -m pip install --upgrade pip


In [494]:
import numpy as np 
from PIL import Image as im 

In [495]:
coef = np.array([0.299, 0.587, 0.114])

In [561]:
def saveImg(img):
    '''
    Вспомогательный метод для записи
    '''
    # img.dtype = np.uint8 # Должен быть uint8
    data = im.fromarray(img)
    data.save('test_gray_img.png')

In [562]:
def readImg(path):
    '''
    Вспомогательный метод для чтения
    '''
    img = im.open(path)
    array = asarray(img)
    return array

In [563]:
def readGrayImgFor(img):
    '''
    Пример 5.1 Через цикл перевод в gray формат
    '''
    imgSize = img.shape
    gimg = []
    for i in range(imgSize[0]):
        for j in range(imgSize[1]):
            gimg.append((img[i][j][0] * coef[0] + img[i][j][0] * coef[0] + img[i][j][0] * coef[0]))
    array = np.array(gimg, dtype=np.uint8)
    return np.reshape(array, (imgSize[0], imgSize[1])) 

In [564]:
def readGrayImgLib(path):
    '''
    Пример 5.2 Используем для перевода в gray библиотечный метод
    https://pillow.readthedocs.io/en/stable/reference/Image.html из документации следует, что такие же к-т
    '''
    img = im.open(path)
    imgGray = img.convert('L')
    imgGray.save('test_gray_img_lib.png')

In [565]:
img = readImg('test.png')
gimg = readGrayImgFor(img)
readGrayImgLib('test.png')
saveImg(gimg)

## Замер скорости работы.

Так сходу различные размеры картинок подготовить не могу, то протестируем на тестовой.

In [566]:
%%timeit
img = readImg('test.png')
gimg = readGrayImgFor(img)
saveImg(gimg)

1.37 s ± 3.54 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [567]:
%%timeit
readGrayImgLib('test.png')

135 ms ± 362 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


## Вывод по 5-ой задаче

Для чтения картинок лучше сразу использовать бибилотечные методы. Методы написанные на python работают слишком медлено.

### 6. Реализовать кодирование длин серий (Run-length encoding). Дан вектор x. Необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить. 
Пример: x = np.array([2, 2, 2, 3, 3, 3, 5, 2, 2]). Ответ: (np.array([2, 3, 5, 2]), np.array([3, 3, 1, 2])).

In [4]:
x = np.array([2, 2, 2, 3, 3, 3, 5, 2, 2])

In [43]:
def EncoderFor(x):
    '''
    Пример 6.1 Через цикл
    '''
    l = [ x[0] ]; r = [ 1 ]
    buf = x[0]
    current_r_i = 0
    for i in range(1, len(x)):
        if buf == x[i]:
            r[current_r_i] += 1
        else:
            buf = x[i]
            l.append(x[i])
            r.append(1)
            current_r_i += 1
    return ( np.array(l), np.array(r))

In [32]:
def EncoderNp(x):
    '''
    Пример 6.2 Использовал numpy
    '''
    parts = np.r_[ True, x[:-1] != x[1:], True ]
    return ( x[parts[:-1]], np.diff(np.flatnonzero(parts)))

In [44]:
def EncoderMult(x):
    '''
    Пример 6.3 Комбинация numpy и циклов
    '''
    indices = np.where(x[:-1] != x[1:])[0]
    indices = np.concatenate((indices, [len(x) - 1]))
    parts = np.split(x, indices + 1)
    parts.pop()
    l = []; r = []
    for it in parts:
        l.append(it[0])
        r.append(len(it))
    return ( np.array(l), np.array(r))

In [45]:
print(EncoderFor(x))
print(EncoderNp(x))
print(EncoderMult(x))

(array([2, 3, 5, 2]), array([3, 3, 1, 2]))


In [46]:
X = [
    np.random.randint(1, 20, 100),
    np.random.randint(1, 20, 1000),
    np.random.randint(1, 20, 10000)
]

100

In [47]:
%%timeit
EncoderFor(X[0])

21.5 µs ± 97.2 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [48]:
%%timeit
EncoderNp(X[0])

6.03 µs ± 54.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [49]:
%%timeit
EncoderMult(X[0])

56.9 µs ± 886 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


1000

In [50]:
%%timeit
EncoderFor(X[1])

211 µs ± 462 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [51]:
%%timeit
EncoderNp(X[1])

7.95 µs ± 41.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [52]:
%%timeit
EncoderMult(X[1])

493 µs ± 3.18 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


10000

In [53]:
%%timeit
EncoderFor(X[2])

2.11 ms ± 3.96 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [54]:
%%timeit
EncoderNp(X[2])

25.7 µs ± 105 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [55]:
%%timeit
EncoderMult(X[2])

4.85 ms ± 13.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Вывод
Использование методов из numpy радикально ускоряет программу. Комбинирование numpy+Python такое чувство в какие то дальние участки памяти переносится и выполняется значительнее медленее.

### 7. Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравнить с функцией scipy.spatial.distance.cdist.

In [95]:
import scipy
import math

In [87]:
X = np.random.randint(-10, 10, size=(5, 5))
print(X)

[[ -5   2   6  -8 -10]
 [  4   7   6   8  -8]
 [  1  -1   3  -2  -2]
 [ -8   0  -3   8   3]
 [  9  -4  -2   3  -9]]


In [167]:
def EuclidFor(X):
    '''
    Пример 7.1 через цикл
    '''
    x = X.copy()
    answer = np.zeros((len(X), len(X[0])))
    i = 0; j = 0
    for str in x:
        for line in X:
            arr = (str - line)
            norm = 0
            for k in range(len(arr)):
                arr[k] = (abs(arr[k])**2)
            norm = sum(arr)
            answer[i][j] = math.sqrt(norm)
            j += 1
        j = 0
        i += 1
    return answer

In [168]:
def EuclidNp(X):
    '''
    Пример 7.2 через numpy
    '''
    P = np.add.outer(np.sum(X**2, axis=1), np.sum(X**2, axis=1))
    N = np.dot(X, X.T)
    return np.sqrt(P - 2*N)

In [165]:
def EuclidScipy(X):
    '''
    Пример 7.3 через scipy
    '''
    return scipy.spatial.distance.cdist(X, X)

In [164]:
print(EuclidFor(X))
print(EuclidNp(X))
print(EuclidScipy(X))

[[ 0.         19.13112647 12.40967365 22.7815715  20.4450483 ]
 [19.13112647  0.         14.76482306 19.87460691 15.3622915 ]
 [12.40967365 14.76482306  0.         15.58845727 13.11487705]
 [22.7815715  19.87460691 15.58845727  0.         21.79449472]
 [20.4450483  15.3622915  13.11487705 21.79449472  0.        ]]
[[ 0.         19.13112647 12.40967365 22.7815715  20.4450483 ]
 [19.13112647  0.         14.76482306 19.87460691 15.3622915 ]
 [12.40967365 14.76482306  0.         15.58845727 13.11487705]
 [22.7815715  19.87460691 15.58845727  0.         21.79449472]
 [20.4450483  15.3622915  13.11487705 21.79449472  0.        ]]
[[ 0.         19.13112647 12.40967365 22.7815715  20.4450483 ]
 [19.13112647  0.         14.76482306 19.87460691 15.3622915 ]
 [12.40967365 14.76482306  0.         15.58845727 13.11487705]
 [22.7815715  19.87460691 15.58845727  0.         21.79449472]
 [20.4450483  15.3622915  13.11487705 21.79449472  0.        ]]


In [169]:
X = [
    np.random.randint(1, 20, size=(100, 100)),
    np.random.randint(1, 20, size=(1000, 1000)),
    np.random.randint(1, 20, size=(10000, 10000))
]

100

In [170]:
%%timeit
EuclidFor(X[0])

151 ms ± 145 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [171]:
%%timeit
EuclidNp(X[0])

375 µs ± 500 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [172]:
%%timeit
EuclidScipy(X[0])

230 µs ± 564 ns per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


1000

In [174]:
%%timeit
EuclidNp(X[1])

352 ms ± 3.27 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [175]:
%%timeit
EuclidScipy(X[1])

260 ms ± 7.47 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Вывод

Метод написанный на python не эффективный. Использование бибилотечных методов хоть и быстро вычисляет данные, но на больших массивах тоже не эффективны.

##### Замечание. Можно считать, что все указанные объекты непустые (к примеру, в задаче №1 на диагонали матрицы есть ненулевые элементы).
Полезные функции NumPy: np.zeros, np.ones, np.diag, np.eye, np.arange, np.linspace, np.meshgrid,
np.random.random, np.random.randint, np.shape, np.reshape, np.transpose, np.any, np.all, np.nonzero, np.where,
np.sum, np.cumsum, np.prod, np.diff, np.min, np.max, np.minimum, np.maximum, np.argmin, np.argmax, np.unique,
np.sort, np.argsort, np.bincount, np.ravel, np.newaxis, np.dot, np.linalg.inv, np.linalg.solve.
Многие из этих функций можно использовать так: x.argmin().

# Для каждой из задач:
(a) Написать на Python + NumPy несколько вариантов кода различной эффективности. Должно быть не
менее трёх вариантов, в том числе как минимум один полностью векторизованный вариант (без циклов), и один
вариант без векторизации (с циклами). Третий вариант решения — на ваше усмотрение, например, это может быть
наиболее хорошо читаемый способ решения, или частично векторизованный вариант. Все пункты выполнять в одном google collab, разделяя их пунктами 1., 1.1, 1.2, 1.3; 2., 2.1, 2.2, 2.3; и тд.

(b) Сравнить в IPython Notebook при помощи %timeit скорость работы на нескольких тестовых наборах
РАЗНОГО размера (минимум 3, причём отличаться размеры входных данных должны минимум на порядок. Например, массивы длины 100, 1000, 10000).

(c) Проанализировать полученные данные о скорости работы разных реализаций.

(d) Получить выводы.

In [ ]:
Soft Deadline - 13 марта в 23:59
Hard Deadline - 20 марта в 23:59